### ISSUE TITLE
#2 Evolution des visuels & identité graphique de l'app

### ISSUE THREAD

**Issue by Ghoslain** [Green-Project/Green#11]

**Comment by YunoL** [comment]
Ajout de la page de configuration ainsi que la page de suggestion des arbres (grid view et dialog pour la visualisation)

**Comment by YunoL** [comment]
Ajout de la page de configuration ainsi que la page de suggestion des arbres (grid view et dialog pour la visualisation)

**Comment by manasies** [comment]
Nouvelle présentation + nouvelle page de login

**Comment by manasies** [comment]
Charte graphique de l'app (couleurs, évolution du logo et du thème en fonction des saisons)
