### ISSUE TITLE
#2 Récupération de données pour l'IA (scrapping, api)

### ISSUE THREAD

**Issue by Ghoslain** [Green-Project/Green#13]

**Comment by Kirian-snx** [comment]
Récupération de chaque plantes de chaque type de chaque catégories a partir de ce site : "https://www.aujardin.info/plantes/"
Création de Json avec toute les infos pour chaque plantes.

**Comment by YerimB** [comment]
Nature des données récupérée :

- Nom
- Nom Scientifique
- Famille
- Origine
- Floraison
- Fleurs
- Type
- Végétation
- Feuillage
- Hauteur
- Rusticité
- Exposition
- Sol
- Acidité
- Humidité
- Utilisation
- Plantation
- Multiplication
- Toxicité

La phase de Data Engineering est prête à commencer
