### ISSUE TITLE
#3 Evolution de l'application

### ISSUE THREAD

**Issue by Ghoslain** [Green-Project/Green#15]
- Rajouter le nouveau login screen 
- Filtre à rajouter sur l'image pour "griser"
- Barre de progression pour la pertinence, barre +/- remplie

**Comment by YunoL** [comment]
link avec la partie IA, changement de thème et ajout d un script pour sélectionner les arbres les plus pertinents

**Comment by Ghoslain** [comment]
+ Affichage de toutes les plantes & arbres avec leurs images & noms sur la partie sélection
