### ISSUE TITLE
#3 Intelligence Artificielle

### ISSUE THREAD

**Issue by Ghoslain** [Green-Project/Green#17]
- Commencer la sélection sur la base des premiers éléments récoltés
- Lier l'IA à l'application

**Comment by Kirian-snx** [comment]
Raffinement des données grâce a de l'ingénierie de donnée.
Lien avec l'application et l'écran de sélection de l'application pour qu'on puisse relier les données raffinées et les données d'entrées. 
Affichage d'une sélection de végétaux correspondant aux données fournis.
